<?php 
include("tokenp.php");
unset($_SESSION["user"]);

unset($_SESSION["nombre"]);
unset($_SESSION["razon_comercial"]);
unset($_SESSION["direccion"]);
unset($_SESSION["telefono_1"]);
unset($_SESSION["ciudad"]);
unset($_SESSION["valid"]);
unset($_SESSION["lista"]);
unset($_SESSION["Saldo_pendiente"]);
unset($_SESSION["cupo"]);
unset($_SESSION["Cupo_Disponible"]);
unset($_SESSION["swc"]);
unset($_SESSION["swf"]);
unset($_SESSION["bloqueo"]);
unset($_SESSION["condicion"]);
unset($_SESSION["vendedor"]);
unset($_SESSION["totalcoste"]);
unset($_SESSION['num_orde']);
unset($_SESSION['carro']);
header("Location:clientes.php");
?>
